### ISSUE TITLE
How to load a map in the karto for the resumption of the karto in uncharted areas

### ISSUE THREAD

**Issue by amburkoff** [ros-perception/open_karto#17]
On the first day, using karto, I create a corridor map and save it via map_saver.
On the second day, I need to load the map into the karto and continue creating the map in the unexplored rooms.
How to save a map from karto so that it can be loaded back into it and continue research in unknown areas?

**Comment by mikeferguson** [comment]
This is not an existing feature of karto. (Or gmapping, where I see you've posted the same question).
